# ================================================
# Configuracion de red del Sistema de Auditorio
# Edita este archivo para cambiar el servidor.
# ================================================
# En la maquina del COMPAÑERO: cambia localhost por la IP del servidor
servidor.ip=localhost
servidor.puerto=5000
